[tool.ruff]
line-length = 100
target-version = "py311"
extend-exclude = ["script.pq"]

[tool.ruff.lint]
select = ["E", "F", "W", "I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
